/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BulkUpdate service. Represents a row in the &quot;hrm_BulkUpdate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.BulkUpdateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.BulkUpdateImpl}.
 * </p>
 *
 * @author rknowsys
 * @see BulkUpdate
 * @see com.rknowsys.eapp.hrm.model.impl.BulkUpdateImpl
 * @see com.rknowsys.eapp.hrm.model.impl.BulkUpdateModelImpl
 * @generated
 */
public interface BulkUpdateModel extends BaseModel<BulkUpdate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bulk update model instance should use the {@link BulkUpdate} interface instead.
	 */

	/**
	 * Returns the primary key of this bulk update.
	 *
	 * @return the primary key of this bulk update
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bulk update.
	 *
	 * @param primaryKey the primary key of this bulk update
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bulkupdate ID of this bulk update.
	 *
	 * @return the bulkupdate ID of this bulk update
	 */
	public long getBulkupdateId();

	/**
	 * Sets the bulkupdate ID of this bulk update.
	 *
	 * @param bulkupdateId the bulkupdate ID of this bulk update
	 */
	public void setBulkupdateId(long bulkupdateId);

	/**
	 * Returns the employee ID of this bulk update.
	 *
	 * @return the employee ID of this bulk update
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this bulk update.
	 *
	 * @param employeeId the employee ID of this bulk update
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the employee no of this bulk update.
	 *
	 * @return the employee no of this bulk update
	 */
	public long getEmployeeNo();

	/**
	 * Sets the employee no of this bulk update.
	 *
	 * @param employeeNo the employee no of this bulk update
	 */
	public void setEmployeeNo(long employeeNo);

	/**
	 * Returns the employee name of this bulk update.
	 *
	 * @return the employee name of this bulk update
	 */
	@AutoEscape
	public String getEmployeeName();

	/**
	 * Sets the employee name of this bulk update.
	 *
	 * @param employeeName the employee name of this bulk update
	 */
	public void setEmployeeName(String employeeName);

	/**
	 * Returns the employment status of this bulk update.
	 *
	 * @return the employment status of this bulk update
	 */
	@AutoEscape
	public String getEmploymentStatus();

	/**
	 * Sets the employment status of this bulk update.
	 *
	 * @param employmentStatus the employment status of this bulk update
	 */
	public void setEmploymentStatus(String employmentStatus);

	/**
	 * Returns the job title of this bulk update.
	 *
	 * @return the job title of this bulk update
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this bulk update.
	 *
	 * @param jobTitle the job title of this bulk update
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the jobtitle ID of this bulk update.
	 *
	 * @return the jobtitle ID of this bulk update
	 */
	public long getJobtitleId();

	/**
	 * Sets the jobtitle ID of this bulk update.
	 *
	 * @param jobtitleId the jobtitle ID of this bulk update
	 */
	public void setJobtitleId(long jobtitleId);

	/**
	 * Returns the subunit of this bulk update.
	 *
	 * @return the subunit of this bulk update
	 */
	@AutoEscape
	public String getSubunit();

	/**
	 * Sets the subunit of this bulk update.
	 *
	 * @param subunit the subunit of this bulk update
	 */
	public void setSubunit(String subunit);

	/**
	 * Returns the subunit ID of this bulk update.
	 *
	 * @return the subunit ID of this bulk update
	 */
	public long getSubunitId();

	/**
	 * Sets the subunit ID of this bulk update.
	 *
	 * @param subunitId the subunit ID of this bulk update
	 */
	public void setSubunitId(long subunitId);

	/**
	 * Returns the location of this bulk update.
	 *
	 * @return the location of this bulk update
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this bulk update.
	 *
	 * @param location the location of this bulk update
	 */
	public void setLocation(String location);

	/**
	 * Returns the location ID of this bulk update.
	 *
	 * @return the location ID of this bulk update
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this bulk update.
	 *
	 * @param locationId the location ID of this bulk update
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the workshift of this bulk update.
	 *
	 * @return the workshift of this bulk update
	 */
	@AutoEscape
	public String getWorkshift();

	/**
	 * Sets the workshift of this bulk update.
	 *
	 * @param workshift the workshift of this bulk update
	 */
	public void setWorkshift(String workshift);

	/**
	 * Returns the shift ID of this bulk update.
	 *
	 * @return the shift ID of this bulk update
	 */
	public long getShiftId();

	/**
	 * Sets the shift ID of this bulk update.
	 *
	 * @param shiftId the shift ID of this bulk update
	 */
	public void setShiftId(long shiftId);

	/**
	 * Returns the joining date of this bulk update.
	 *
	 * @return the joining date of this bulk update
	 */
	public Date getJoiningDate();

	/**
	 * Sets the joining date of this bulk update.
	 *
	 * @param joiningDate the joining date of this bulk update
	 */
	public void setJoiningDate(Date joiningDate);

	/**
	 * Returns the supervisor of this bulk update.
	 *
	 * @return the supervisor of this bulk update
	 */
	@AutoEscape
	public String getSupervisor();

	/**
	 * Sets the supervisor of this bulk update.
	 *
	 * @param supervisor the supervisor of this bulk update
	 */
	public void setSupervisor(String supervisor);

	/**
	 * Returns the emp status of this bulk update.
	 *
	 * @return the emp status of this bulk update
	 */
	public long getEmpStatus();

	/**
	 * Sets the emp status of this bulk update.
	 *
	 * @param empStatus the emp status of this bulk update
	 */
	public void setEmpStatus(long empStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BulkUpdate bulkUpdate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BulkUpdate> toCacheModel();

	@Override
	public BulkUpdate toEscapedModel();

	@Override
	public BulkUpdate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}