/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DocumentCategories service. Represents a row in the &quot;document_categories&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.DocumentCategoriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.DocumentCategoriesImpl}.
 * </p>
 *
 * @author rknowsys
 * @see DocumentCategories
 * @see com.rknowsys.eapp.hrm.model.impl.DocumentCategoriesImpl
 * @see com.rknowsys.eapp.hrm.model.impl.DocumentCategoriesModelImpl
 * @generated
 */
public interface DocumentCategoriesModel extends BaseModel<DocumentCategories> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document categories model instance should use the {@link DocumentCategories} interface instead.
	 */

	/**
	 * Returns the primary key of this document categories.
	 *
	 * @return the primary key of this document categories
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document categories.
	 *
	 * @param primaryKey the primary key of this document categories
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the documentcategory ID of this document categories.
	 *
	 * @return the documentcategory ID of this document categories
	 */
	public long getDocumentcategoryId();

	/**
	 * Sets the documentcategory ID of this document categories.
	 *
	 * @param documentcategoryId the documentcategory ID of this document categories
	 */
	public void setDocumentcategoryId(long documentcategoryId);

	/**
	 * Returns the company ID of this document categories.
	 *
	 * @return the company ID of this document categories
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this document categories.
	 *
	 * @param companyId the company ID of this document categories
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this document categories.
	 *
	 * @return the group ID of this document categories
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this document categories.
	 *
	 * @param groupId the group ID of this document categories
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this document categories.
	 *
	 * @return the user ID of this document categories
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this document categories.
	 *
	 * @param userId the user ID of this document categories
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this document categories.
	 *
	 * @return the user uuid of this document categories
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this document categories.
	 *
	 * @param userUuid the user uuid of this document categories
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this document categories.
	 *
	 * @return the create date of this document categories
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this document categories.
	 *
	 * @param createDate the create date of this document categories
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document categories.
	 *
	 * @return the modified date of this document categories
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document categories.
	 *
	 * @param modifiedDate the modified date of this document categories
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the document category of this document categories.
	 *
	 * @return the document category of this document categories
	 */
	@AutoEscape
	public String getDocumentCategory();

	/**
	 * Sets the document category of this document categories.
	 *
	 * @param documentCategory the document category of this document categories
	 */
	public void setDocumentCategory(String documentCategory);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DocumentCategories documentCategories);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DocumentCategories> toCacheModel();

	@Override
	public DocumentCategories toEscapedModel();

	@Override
	public DocumentCategories toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}