/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LeaveAccrual service. Represents a row in the &quot;leave_accrual&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.LeaveAccrualModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.LeaveAccrualImpl}.
 * </p>
 *
 * @author rknowsys
 * @see LeaveAccrual
 * @see com.rknowsys.eapp.hrm.model.impl.LeaveAccrualImpl
 * @see com.rknowsys.eapp.hrm.model.impl.LeaveAccrualModelImpl
 * @generated
 */
public interface LeaveAccrualModel extends BaseModel<LeaveAccrual> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave accrual model instance should use the {@link LeaveAccrual} interface instead.
	 */

	/**
	 * Returns the primary key of this leave accrual.
	 *
	 * @return the primary key of this leave accrual
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave accrual.
	 *
	 * @param primaryKey the primary key of this leave accrual
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the leave accrual ID of this leave accrual.
	 *
	 * @return the leave accrual ID of this leave accrual
	 */
	public long getLeaveAccrualId();

	/**
	 * Sets the leave accrual ID of this leave accrual.
	 *
	 * @param leaveAccrualId the leave accrual ID of this leave accrual
	 */
	public void setLeaveAccrualId(long leaveAccrualId);

	/**
	 * Returns the company ID of this leave accrual.
	 *
	 * @return the company ID of this leave accrual
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave accrual.
	 *
	 * @param companyId the company ID of this leave accrual
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this leave accrual.
	 *
	 * @return the group ID of this leave accrual
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave accrual.
	 *
	 * @param groupId the group ID of this leave accrual
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this leave accrual.
	 *
	 * @return the create date of this leave accrual
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave accrual.
	 *
	 * @param createDate the create date of this leave accrual
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave accrual.
	 *
	 * @return the modified date of this leave accrual
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave accrual.
	 *
	 * @param modifiedDate the modified date of this leave accrual
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this leave accrual.
	 *
	 * @return the user ID of this leave accrual
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this leave accrual.
	 *
	 * @param userId the user ID of this leave accrual
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave accrual.
	 *
	 * @return the user uuid of this leave accrual
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this leave accrual.
	 *
	 * @param userUuid the user uuid of this leave accrual
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the leave type ID of this leave accrual.
	 *
	 * @return the leave type ID of this leave accrual
	 */
	public long getLeaveTypeId();

	/**
	 * Sets the leave type ID of this leave accrual.
	 *
	 * @param leaveTypeId the leave type ID of this leave accrual
	 */
	public void setLeaveTypeId(long leaveTypeId);

	/**
	 * Returns the accrual frequency of this leave accrual.
	 *
	 * @return the accrual frequency of this leave accrual
	 */
	@AutoEscape
	public String getAccrualFrequency();

	/**
	 * Sets the accrual frequency of this leave accrual.
	 *
	 * @param accrualFrequency the accrual frequency of this leave accrual
	 */
	public void setAccrualFrequency(String accrualFrequency);

	/**
	 * Returns the accrue every of this leave accrual.
	 *
	 * @return the accrue every of this leave accrual
	 */
	public int getAccrueEvery();

	/**
	 * Sets the accrue every of this leave accrual.
	 *
	 * @param accrueEvery the accrue every of this leave accrual
	 */
	public void setAccrueEvery(int accrueEvery);

	/**
	 * Returns the day of credit of this leave accrual.
	 *
	 * @return the day of credit of this leave accrual
	 */
	public int getDayOfCredit();

	/**
	 * Sets the day of credit of this leave accrual.
	 *
	 * @param dayOfCredit the day of credit of this leave accrual
	 */
	public void setDayOfCredit(int dayOfCredit);

	/**
	 * Returns the accrual starts on of this leave accrual.
	 *
	 * @return the accrual starts on of this leave accrual
	 */
	@AutoEscape
	public String getAccrualStartsOn();

	/**
	 * Sets the accrual starts on of this leave accrual.
	 *
	 * @param accrualStartsOn the accrual starts on of this leave accrual
	 */
	public void setAccrualStartsOn(String accrualStartsOn);

	/**
	 * Returns the month of credit of this leave accrual.
	 *
	 * @return the month of credit of this leave accrual
	 */
	public int getMonthOfCredit();

	/**
	 * Sets the month of credit of this leave accrual.
	 *
	 * @param monthOfCredit the month of credit of this leave accrual
	 */
	public void setMonthOfCredit(int monthOfCredit);

	/**
	 * Returns the accrual valid from of this leave accrual.
	 *
	 * @return the accrual valid from of this leave accrual
	 */
	@AutoEscape
	public String getAccrualValidFrom();

	/**
	 * Sets the accrual valid from of this leave accrual.
	 *
	 * @param accrualValidFrom the accrual valid from of this leave accrual
	 */
	public void setAccrualValidFrom(String accrualValidFrom);

	/**
	 * Returns the first accrual of this leave accrual.
	 *
	 * @return the first accrual of this leave accrual
	 */
	@AutoEscape
	public String getFirstAccrual();

	/**
	 * Sets the first accrual of this leave accrual.
	 *
	 * @param firstAccrual the first accrual of this leave accrual
	 */
	public void setFirstAccrual(String firstAccrual);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LeaveAccrual leaveAccrual);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LeaveAccrual> toCacheModel();

	@Override
	public LeaveAccrual toEscapedModel();

	@Override
	public LeaveAccrual toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}