/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rknowsys.eapp.hrm.model.DocumentsAttachments;
import com.rknowsys.eapp.hrm.service.DocumentsAttachmentsLocalServiceUtil;

/**
 * The extended model base implementation for the DocumentsAttachments service. Represents a row in the &quot;documents_attachments&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentsAttachmentsImpl}.
 * </p>
 *
 * @author rknowsys
 * @see DocumentsAttachmentsImpl
 * @see com.rknowsys.eapp.hrm.model.DocumentsAttachments
 * @generated
 */
public abstract class DocumentsAttachmentsBaseImpl
	extends DocumentsAttachmentsModelImpl implements DocumentsAttachments {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a documents attachments model instance should use the {@link DocumentsAttachments} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			DocumentsAttachmentsLocalServiceUtil.addDocumentsAttachments(this);
		}
		else {
			DocumentsAttachmentsLocalServiceUtil.updateDocumentsAttachments(this);
		}
	}
}