/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.DocumentCategories;
import com.rknowsys.eapp.hrm.model.DocumentCategoriesModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DocumentCategories service. Represents a row in the &quot;document_categories&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.DocumentCategoriesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentCategoriesImpl}.
 * </p>
 *
 * @author rknowsys
 * @see DocumentCategoriesImpl
 * @see com.rknowsys.eapp.hrm.model.DocumentCategories
 * @see com.rknowsys.eapp.hrm.model.DocumentCategoriesModel
 * @generated
 */
public class DocumentCategoriesModelImpl extends BaseModelImpl<DocumentCategories>
	implements DocumentCategoriesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document categories model instance should use the {@link com.rknowsys.eapp.hrm.model.DocumentCategories} interface instead.
	 */
	public static final String TABLE_NAME = "document_categories";
	public static final Object[][] TABLE_COLUMNS = {
			{ "documentcategoryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "documentCategory", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table document_categories (documentcategoryId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,documentCategory VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table document_categories";
	public static final String ORDER_BY_JPQL = " ORDER BY documentCategories.documentcategoryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY document_categories.documentcategoryId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.DocumentCategories"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.DocumentCategories"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.DocumentCategories"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long DOCUMENTCATEGORYID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.DocumentCategories"));

	public DocumentCategoriesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _documentcategoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDocumentcategoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _documentcategoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DocumentCategories.class;
	}

	@Override
	public String getModelClassName() {
		return DocumentCategories.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("documentcategoryId", getDocumentcategoryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("documentCategory", getDocumentCategory());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long documentcategoryId = (Long)attributes.get("documentcategoryId");

		if (documentcategoryId != null) {
			setDocumentcategoryId(documentcategoryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String documentCategory = (String)attributes.get("documentCategory");

		if (documentCategory != null) {
			setDocumentCategory(documentCategory);
		}
	}

	@Override
	public long getDocumentcategoryId() {
		return _documentcategoryId;
	}

	@Override
	public void setDocumentcategoryId(long documentcategoryId) {
		_documentcategoryId = documentcategoryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getDocumentCategory() {
		if (_documentCategory == null) {
			return StringPool.BLANK;
		}
		else {
			return _documentCategory;
		}
	}

	@Override
	public void setDocumentCategory(String documentCategory) {
		_documentCategory = documentCategory;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DocumentCategories.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DocumentCategories toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DocumentCategories)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DocumentCategoriesImpl documentCategoriesImpl = new DocumentCategoriesImpl();

		documentCategoriesImpl.setDocumentcategoryId(getDocumentcategoryId());
		documentCategoriesImpl.setCompanyId(getCompanyId());
		documentCategoriesImpl.setGroupId(getGroupId());
		documentCategoriesImpl.setUserId(getUserId());
		documentCategoriesImpl.setCreateDate(getCreateDate());
		documentCategoriesImpl.setModifiedDate(getModifiedDate());
		documentCategoriesImpl.setDocumentCategory(getDocumentCategory());

		documentCategoriesImpl.resetOriginalValues();

		return documentCategoriesImpl;
	}

	@Override
	public int compareTo(DocumentCategories documentCategories) {
		long primaryKey = documentCategories.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DocumentCategories)) {
			return false;
		}

		DocumentCategories documentCategories = (DocumentCategories)obj;

		long primaryKey = documentCategories.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DocumentCategoriesModelImpl documentCategoriesModelImpl = this;

		documentCategoriesModelImpl._originalGroupId = documentCategoriesModelImpl._groupId;

		documentCategoriesModelImpl._setOriginalGroupId = false;

		documentCategoriesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DocumentCategories> toCacheModel() {
		DocumentCategoriesCacheModel documentCategoriesCacheModel = new DocumentCategoriesCacheModel();

		documentCategoriesCacheModel.documentcategoryId = getDocumentcategoryId();

		documentCategoriesCacheModel.companyId = getCompanyId();

		documentCategoriesCacheModel.groupId = getGroupId();

		documentCategoriesCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			documentCategoriesCacheModel.createDate = createDate.getTime();
		}
		else {
			documentCategoriesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			documentCategoriesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			documentCategoriesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		documentCategoriesCacheModel.documentCategory = getDocumentCategory();

		String documentCategory = documentCategoriesCacheModel.documentCategory;

		if ((documentCategory != null) && (documentCategory.length() == 0)) {
			documentCategoriesCacheModel.documentCategory = null;
		}

		return documentCategoriesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{documentcategoryId=");
		sb.append(getDocumentcategoryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", documentCategory=");
		sb.append(getDocumentCategory());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.DocumentCategories");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>documentcategoryId</column-name><column-value><![CDATA[");
		sb.append(getDocumentcategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentCategory</column-name><column-value><![CDATA[");
		sb.append(getDocumentCategory());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DocumentCategories.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DocumentCategories.class
		};
	private long _documentcategoryId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _documentCategory;
	private long _columnBitmask;
	private DocumentCategories _escapedModel;
}