/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rknowsys.eapp.hrm.model.LeaveAccrual;
import com.rknowsys.eapp.hrm.service.LeaveAccrualLocalServiceUtil;

/**
 * The extended model base implementation for the LeaveAccrual service. Represents a row in the &quot;leave_accrual&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveAccrualImpl}.
 * </p>
 *
 * @author rknowsys
 * @see LeaveAccrualImpl
 * @see com.rknowsys.eapp.hrm.model.LeaveAccrual
 * @generated
 */
public abstract class LeaveAccrualBaseImpl extends LeaveAccrualModelImpl
	implements LeaveAccrual {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave accrual model instance should use the {@link LeaveAccrual} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			LeaveAccrualLocalServiceUtil.addLeaveAccrual(this);
		}
		else {
			LeaveAccrualLocalServiceUtil.updateLeaveAccrual(this);
		}
	}
}